"""
File Upload Service

Business logic for file uploads with storage-backend-agnostic URL generation
and quota management. Supports local filesystem (dev) and S3 (cloud) via the
FileStorage abstraction — swap get_file_storage() for Azure Blob when needed.
"""

import logging
import os
import uuid
from datetime import datetime, timedelta, timezone
from typing import List, Optional

from apis.shared.files.models import (
    FileMetadata,
    FileStatus,
    PresignRequest,
    PresignResponse,
    CompleteUploadResponse,
    FileResponse,
    FileListResponse,
    QuotaResponse,
    is_allowed_mime_type,
    ALLOWED_MIME_TYPES,
)
from apis.shared.files.repository import FileUploadRepository, get_file_upload_repository
from apis.shared.storage import get_file_storage, FileStorage

logger = logging.getLogger(__name__)


class FileUploadError(Exception):
    """Base exception for file upload errors."""


class QuotaExceededError(FileUploadError):
    def __init__(self, current_usage: int, max_allowed: int, required_space: int):
        self.current_usage = current_usage
        self.max_allowed = max_allowed
        self.required_space = required_space
        super().__init__(
            f"Storage quota exceeded: {current_usage}/{max_allowed} bytes, "
            f"need {required_space} more bytes"
        )


class InvalidFileTypeError(FileUploadError):
    def __init__(self, mime_type: str):
        self.mime_type = mime_type
        allowed = ", ".join(ALLOWED_MIME_TYPES.values())
        super().__init__(f"Invalid file type: {mime_type}. Allowed types: {allowed}")


class FileTooLargeError(FileUploadError):
    def __init__(self, size_bytes: int, max_size: int):
        self.size_bytes = size_bytes
        self.max_size = max_size
        super().__init__(f"File too large: {size_bytes} bytes. Maximum: {max_size} bytes")


class FileNotFoundError(FileUploadError):
    pass


class FileUploadService:
    """
    Storage-backend-agnostic file upload service.

    The presigned/upload URL is generated by the injected FileStorage — S3
    presigned PUT or a local app-API endpoint, depending on the backend.
    """

    def __init__(
        self,
        repository: Optional[FileUploadRepository] = None,
        storage: Optional[FileStorage] = None,
        max_file_size: Optional[int] = None,
        max_files_per_message: Optional[int] = None,
        user_quota_bytes: Optional[int] = None,
    ):
        self.repository = repository or get_file_upload_repository()
        self._storage = storage or get_file_storage()

        self.max_file_size = max_file_size or int(
            os.environ.get("FILE_UPLOAD_MAX_SIZE_BYTES", 4 * 1024 * 1024)  # 4 MB
        )
        self.max_files_per_message = max_files_per_message or int(
            os.environ.get("FILE_UPLOAD_MAX_FILES_PER_MESSAGE", 5)
        )
        self.user_quota_bytes = user_quota_bytes or int(
            os.environ.get("FILE_UPLOAD_USER_QUOTA_BYTES", 1024 * 1024 * 1024)  # 1 GB
        )
        self._presign_expiration = 15 * 60  # 15 minutes

    # -------------------------------------------------------------------------
    # Upload flow
    # -------------------------------------------------------------------------

    async def request_presigned_url(
        self, user_id: str, request: PresignRequest
    ) -> PresignResponse:
        """Phase 1: validate, create metadata, return upload URL."""
        if not is_allowed_mime_type(request.mime_type):
            raise InvalidFileTypeError(request.mime_type)

        if request.size_bytes > self.max_file_size:
            raise FileTooLargeError(request.size_bytes, self.max_file_size)

        quota = await self.repository.get_user_quota(user_id)
        if quota.total_bytes + request.size_bytes > self.user_quota_bytes:
            raise QuotaExceededError(
                current_usage=quota.total_bytes,
                max_allowed=self.user_quota_bytes,
                required_space=request.size_bytes,
            )

        timestamp_hex = format(int(datetime.now(timezone.utc).timestamp() * 1000), "x")
        upload_id = f"{timestamp_hex}_{uuid.uuid4().hex[:16]}"
        storage_key = f"user-files/{user_id}/{request.session_id}/{upload_id}/{request.filename}"

        file_meta = FileMetadata(
            upload_id=upload_id,
            user_id=user_id,
            session_id=request.session_id,
            filename=request.filename,
            mime_type=request.mime_type,
            size_bytes=request.size_bytes,
            storage_key=storage_key,
            storage_bucket="",
            status=FileStatus.PENDING,
        )
        await self.repository.create_file(file_meta)

        try:
            upload_url = await self._storage.get_upload_url(
                upload_id=upload_id,
                key=storage_key,
                content_type=request.mime_type,
                expires_in=self._presign_expiration,
            )
        except Exception:
            await self.repository.delete_file(user_id, upload_id)
            logger.error("Failed to generate upload URL for %s", upload_id, exc_info=True)
            raise

        expires_at = (
            datetime.now(timezone.utc) + timedelta(seconds=self._presign_expiration)
        ).isoformat() + "Z"

        logger.info("Upload URL generated: upload_id=%s user=%s", upload_id, user_id)
        return PresignResponse(
            upload_id=upload_id,
            presigned_url=upload_url,
            expires_at=expires_at,
        )

    async def complete_upload(self, user_id: str, upload_id: str) -> CompleteUploadResponse:
        """Phase 2: verify file exists in storage, mark READY, increment quota."""
        file_meta = await self.repository.get_file(user_id, upload_id)
        if not file_meta:
            raise FileNotFoundError(f"Upload {upload_id} not found")

        if file_meta.status != FileStatus.PENDING:
            raise FileUploadError(
                f"Upload {upload_id} is already {file_meta.status}, cannot complete"
            )

        if not await self._storage.exists(file_meta.storage_key):
            await self.repository.update_file_status(user_id, upload_id, FileStatus.FAILED)
            raise FileNotFoundError(f"File content not found in storage for upload {upload_id}")

        await self.repository.update_file_status(user_id, upload_id, FileStatus.READY)
        await self.repository.increment_quota(user_id, file_meta.size_bytes)

        logger.info("Upload completed: upload_id=%s", upload_id)
        return CompleteUploadResponse(
            upload_id=upload_id,
            status=FileStatus.READY.value,
            storage_uri=file_meta.storage_uri,
            filename=file_meta.filename,
            size_bytes=file_meta.size_bytes,
        )

    # -------------------------------------------------------------------------
    # File management
    # -------------------------------------------------------------------------

    async def get_file(self, user_id: str, upload_id: str) -> Optional[FileMetadata]:
        return await self.repository.get_file(user_id, upload_id)

    async def delete_file(self, user_id: str, upload_id: str) -> bool:
        file_meta = await self.repository.get_file(user_id, upload_id)
        if not file_meta:
            return False

        try:
            await self._storage.delete(file_meta.storage_key)
        except Exception:
            logger.warning("Storage delete failed for upload %s", upload_id, exc_info=True)

        deleted = await self.repository.delete_file(user_id, upload_id)
        if deleted and file_meta.status == FileStatus.READY:
            await self.repository.decrement_quota(user_id, file_meta.size_bytes)

        return bool(deleted)

    async def list_user_files(
        self,
        user_id: str,
        session_id: Optional[str] = None,
        limit: int = 20,
        cursor: Optional[str] = None,
        sort_by: str = "date",
        sort_order: str = "desc",
    ) -> FileListResponse:
        if session_id:
            files = await self.repository.list_session_files(session_id, status=FileStatus.READY)
            files = [f for f in files if f.user_id == user_id]
            files = self._sort_files(files, sort_by, sort_order)
            return FileListResponse(
                files=[FileResponse.from_metadata(f) for f in files[:limit]],
                next_cursor=None if len(files) <= limit else "more",
                total_count=len(files),
            )
        else:
            files, next_cursor = await self.repository.list_user_files(
                user_id, limit=limit, cursor=cursor, status=FileStatus.READY
            )
            files = self._sort_files(files, sort_by, sort_order)
            return FileListResponse(
                files=[FileResponse.from_metadata(f) for f in files],
                next_cursor=next_cursor,
                total_count=None,
            )

    def _sort_files(self, files: List[FileMetadata], sort_by: str, sort_order: str) -> List[FileMetadata]:
        reverse = sort_order == "desc"
        if sort_by == "size":
            return sorted(files, key=lambda f: f.size_bytes, reverse=reverse)
        if sort_by == "type":
            return sorted(files, key=lambda f: f.mime_type, reverse=reverse)
        return sorted(files, key=lambda f: f.created_at, reverse=reverse)

    async def get_session_files(self, session_id: str) -> List[FileMetadata]:
        return await self.repository.list_session_files(session_id, status=FileStatus.READY)

    async def delete_session_files(self, session_id: str) -> int:
        files = await self.repository.list_session_files(session_id, status=None)
        if not files:
            return 0

        deleted_count = 0
        for file_meta in files:
            try:
                await self._storage.delete(file_meta.storage_key)
                deleted = await self.repository.delete_file(file_meta.user_id, file_meta.upload_id)
                if deleted and file_meta.status == FileStatus.READY:
                    await self.repository.decrement_quota(file_meta.user_id, file_meta.size_bytes)
                deleted_count += 1
            except Exception:
                logger.warning("Cascade delete failed for %s", file_meta.upload_id, exc_info=True)

        logger.info("Cascade deleted %d/%d files for session %s", deleted_count, len(files), session_id)
        return deleted_count

    async def get_user_quota(self, user_id: str) -> QuotaResponse:
        quota = await self.repository.get_user_quota(user_id)
        return QuotaResponse(
            used_bytes=quota.total_bytes,
            max_bytes=self.user_quota_bytes,
            file_count=quota.file_count,
        )


_service_instance: Optional[FileUploadService] = None


def get_file_upload_service() -> FileUploadService:
    global _service_instance
    if _service_instance is None:
        _service_instance = FileUploadService()
    return _service_instance
